/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2020-05-23 03:43:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.13.0/css/all.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css\">\r\n");
      out.write("\t <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write("    <title>The Journey (2018-2020) </title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-light bg-light sticky-top\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"index.html\"><img src=\"resources/logo4.png\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t<a class=\"nav-link \" href=\"#\">Home</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link \" href=\"#\">Gallery</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link \" href=\"#\">Events</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link \" href=\"#\">Extras</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<a class=\"nav-link \" href=\"#\">FeedBack \t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <!-- Carrousel -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"slides\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t<ul class=\"carousel-indicators\">\r\n");
      out.write("\t\t<li data-target=\"#slides\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t<li data-target=\"#slides\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t<li data-target=\"#slides\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"carousel-inner\">\r\n");
      out.write("\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t<img src=\"resources/c1.jpg\">\r\n");
      out.write("\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t<h3 class=\"display-4\">Idiots in Line</h3>\r\n");
      out.write("\t\t<h2>Have a look at them</h2>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-outline-light btn-lg\">Demo</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t<img src=\"resources/c2.jpg\">\r\n");
      out.write("\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t<h3 class=\"display-4\">Our faculties</h3>\r\n");
      out.write("\t\t<h2></h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t<img src=\"resources/c3.jpg\">\r\n");
      out.write("\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t<h3 class=\"display-4\">Idiots in Line</h3>\r\n");
      out.write("\t\t<h2>They are back!</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Jumbotron -->\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row jumbotron\">\r\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-9 col-xl-10\">\r\n");
      out.write("\t<p>A lot has happened this year it's just not possible to explain it with a few words</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2\">\r\n");
      out.write("\t<a href=\"#\"><button type=\"button\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("\tGallery</button></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Three Cards -->\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row welome text-center\">\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t<h1 class=\"display-4\">We took Mca</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t<p class=\"lead\"> The purpose of our lives is to be happy.â â Dalai Lama.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- THree column section -->\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row text-center padding\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t<i class=\"fab fa-java fa-2x\"></i>\r\n");
      out.write("\t\t\t<h3>Java</h3>\r\n");
      out.write("\t\t\t<p>The best thing.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t<i class=\"fab fa-python fa-3x\"></i>\r\n");
      out.write("\t\t\t<h3>Python</h3>\r\n");
      out.write("\t\t\t<p>I've the certificate.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12  col-md-4\" >\r\n");
      out.write("\t\t\t<i class=\"fab fa-php fa-3x\"></i>\r\n");
      out.write("\t\t\t<h3>PHP</h3>\r\n");
      out.write("\t\t\t<p>Those days!!</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr class=\"my-4\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Two column section -->\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row padding\">\r\n");
      out.write("\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t<h2>Life is a roller coaster</h2>\r\n");
      out.write("\t\t<p>Life brings us as many joyful moments as it does downfalls, and although there are days we wish there was a manual to follow, it simply wouldnât be the same without the spontaneity.</p>\r\n");
      out.write("\t\t<p>Whether youâre embarking on a new adventure right out of school or you want to explore different paths in your personal life, itâs never too late to change what the future looks like.</p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<a href=\"#\" class=\"btn btn-primary\">Go to college website</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t<div class=\"bord\">\r\n");
      out.write("\t\t\t<img src=\"resources/c5.jpg\" class=\"img-fluid padding\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr class=\"my-4\">\r\n");
      out.write("\t<!-- Backdrop static background -->\r\n");
      out.write("\t<figure>\r\n");
      out.write("\t<div class=\"fixed-wrap\">\r\n");
      out.write("\t\t<div id=\"fixed\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div >\r\n");
      out.write("\t</figure>\r\n");
      out.write("\t<!-- Hidden Emoji Section -->\r\n");
      out.write("\t<button class=\"fun\" data-toggle=\"collapse\" data-target=\"#emoji\"> Click for something interesting\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<div id=\"emoji\" class=\"collapse\">\r\n");
      out.write("\t\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"gif\" src=\"gifs\\compass\\animat-compass-color.gif\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"gif\" src=\"gifs\\road-trip\\animat-road-trip-color.gif\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"gif\" src=\"gifs\\day-night\\animat-day-night.gif\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"gif\" src=\"gifs\\swiss-knife\\animat-swiss-knife-color.gif\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Meet the partners in Crime -->\r\n");
      out.write("\t<div class=\"container-fluid\" >\r\n");
      out.write("\t\t<div class=\"row welcome text-center\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<h1 class=\"display-4\" >Meet the Partners</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Cards-->\r\n");
      out.write("\t\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row padding\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"resources/t1.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"card-title\" >Prakash</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\" >ma'am actually</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-outline-secondary\">know more</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"resources/t3.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"card-title\" >Ezra</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\" >Hey! bhaiya!</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-outline-secondary\">know more</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"resources/t5.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"card-title\" >Umar</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\" >PUBG maar! maar! maar!</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-outline-secondary\">know more</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"resources/t2.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"card-title\" >Aetesham</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\" >Assalam Valikum</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-outline-secondary\">know more</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- ;Quotes Section Cards -->\r\n");
      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row welome text-center\">\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t<h1 class=\"display-4\">It's all bad Decisions.</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t<p class=\"lead\">\"Friendship is so weird...you just pick a human you've met and you're like 'Yep, I like this one' and you just do stuff with them.\" </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<!-- Two column section 2 -->\r\n");
      out.write("\t\t<hr class=\"my-4\">\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row padding\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t<h2>The Trips</h2>\r\n");
      out.write("\t\t\t<p>Been to Nasa As well</p>\r\n");
      out.write("\t\t\t<p>didn't get a chance to go to space though.</p>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btn btn-primary\">Trips Gallery</a>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t<img src=\"resources/n1.jpg\" class=\"img-fluid padding\">\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr class=\"my-4\">\r\n");
      out.write("\t<!-- Socila media -->\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row text-center padding\">\r\n");
      out.write("\t\t<div class=\"col-12\" >\r\n");
      out.write("\t\t<h2>Follow me on </h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-12 social padding\">\r\n");
      out.write("\t\t<a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("\t\t<a href=\"https://www.reddit.com/user/chirag8460\"><i class=\"fab fa-reddit\"></i></a>\r\n");
      out.write("\t\t<a href=\"https://www.linkedin.com/in/chirag-kaushik-094875175/\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("\t\t<a href=\"https://twitter.com/chirag_72\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("\t\t<a href=\"https://www.quora.com/profile/Chirag-Kaushik-6\"><i class=\"fab fa-quora\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("    <!--footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t<div class=\"row text-center\">\r\n");
      out.write("\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t<img src=\"resources/logo4.png\">\r\n");
      out.write("\t\t<hr class=\"light\">\r\n");
      out.write("\t\t<p>8460673166</p>\r\n");
      out.write("\t\t<p>chiragkaushik555@gmail.com</p>\r\n");
      out.write("\t\t<p>India</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t<hr class=\"light\">\r\n");
      out.write("\t\t<p>Our Hours</p>\r\n");
      out.write("\t\t<hr class=\"light\">\r\n");
      out.write("\t\t<p>Weekdays : 10am - 4pm</p>\r\n");
      out.write("\t\t<p>Weekends : 10am - 4pm</p>\r\n");
      out.write("\t\t<p>India</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t<hr class=\"light\">\r\n");
      out.write("\t\t<p>Our Offices at</p>\r\n");
      out.write("\t\t<hr class=\"light\">\r\n");
      out.write("\t\t<p>Vadodara, Gujarat</p>\r\n");
      out.write("\t\t<p>Vapi, Gujarat</p>\r\n");
      out.write("\t\t<p>Ahmedabad, Gujarat</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-12\">\r\n");
      out.write("\t<hr class=\"light \">\r\n");
      out.write("\t<h5>&copy; chiragk.com</h5>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
